"""focus violation count on exam sessions

Revision ID: 2e4b54596555
Revises: 67f4674a19af
Create Date: 2026-09-10 18:56:01.227219
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2e4b54596555'
down_revision: str | None = '67f4674a19af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('focus_violation_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'focus_violation_count')
    # ### end Alembic commands ###
