"""question provenance and exam-only questions

Revision ID: 67f4674a19af
Revises: 737b6543331b
Create Date: 2026-09-10 16:45:13.681058
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '67f4674a19af'
down_revision: str | None = '737b6543331b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Declared once and created/dropped explicitly. Left to add_column/drop_column, the
# Postgres TYPE is created implicitly but never removed, so a downgrade followed by a
# re-upgrade fails with "type question_source already exists".
question_source = sa.Enum('manual', 'ai_generated', 'imported', name='question_source')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    question_source.create(op.get_bind(), checkfirst=True)
    op.add_column('questions', sa.Column('source', question_source, server_default='manual', nullable=False))
    op.add_column('questions', sa.Column('origin_exam_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_questions_origin_exam_id'), 'questions', ['origin_exam_id'], unique=False)
    op.create_index(op.f('ix_questions_source'), 'questions', ['source'], unique=False)
    op.create_foreign_key(op.f('fk_questions_origin_exam_id_exams'), 'questions', 'exams', ['origin_exam_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_questions_origin_exam_id_exams'), 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_source'), table_name='questions')
    op.drop_index(op.f('ix_questions_origin_exam_id'), table_name='questions')
    op.drop_column('questions', 'origin_exam_id')
    op.drop_column('questions', 'source')
    question_source.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
