"""add_answer_review_flag

Revision ID: a7d787ede8d4
Revises: c4d07b8e1a92
Create Date: 2026-09-04 01:03:37.293580
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a7d787ede8d4'
down_revision: str | None = 'c4d07b8e1a92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_review_flagged', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'is_review_flagged')
    # ### end Alembic commands ###
