"""login access requests, exam enrollments, split names

Revision ID: f0c6eeb2272c
Revises: 03ad33e6bd09
Create Date: 2026-08-27 16:44:14.186364
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'f0c6eeb2272c'
down_revision: str | None = '03ad33e6bd09'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_access_requests',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='login_access_status'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], name=op.f('fk_login_access_requests_candidate_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_login_access_requests_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_access_requests'))
    )
    op.create_index(op.f('ix_login_access_requests_candidate_id'), 'login_access_requests', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_login_access_requests_status'), 'login_access_requests', ['status'], unique=False)
    op.create_table('exam_enrollments',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_exam_enrollments_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], name=op.f('fk_exam_enrollments_candidate_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_enrollments_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_enrollments')),
    sa.UniqueConstraint('exam_id', 'candidate_id', name='uq_exam_enrollment')
    )
    op.create_index(op.f('ix_exam_enrollments_candidate_id'), 'exam_enrollments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_exam_enrollments_exam_id'), 'exam_enrollments', ['exam_id'], unique=False)
    # Added with a server default so the columns can be NOT NULL on a populated table;
    # the default is dropped again once the backfill below has run.
    op.add_column(
        'users',
        sa.Column('first_name', sa.String(length=80), nullable=False, server_default=''),
    )
    op.add_column(
        'users',
        sa.Column('last_name', sa.String(length=80), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###

    # --- data migration -----------------------------------------------------
    # Split existing full names: everything before the first space is the first name,
    # the remainder is the last name. Nothing is deleted and full_name is left intact.
    op.execute(
        """
        UPDATE users
           SET first_name = split_part(trim(full_name), ' ', 1),
               last_name  = trim(substr(trim(full_name),
                                        length(split_part(trim(full_name), ' ', 1)) + 1))
         WHERE first_name = ''
        """
    )
    op.alter_column('users', 'first_name', server_default=None)
    op.alter_column('users', 'last_name', server_default=None)

    # Existing candidates were already using the platform, so grandfather them in as
    # approved rather than locking everyone out behind a new pending gate.
    op.execute(
        """
        INSERT INTO login_access_requests
              (id, candidate_id, status, requested_at, reviewed_at, review_note,
               created_at, updated_at)
        SELECT gen_random_uuid(), u.id, 'approved', u.created_at, now(),
               'Granted automatically when login approval was introduced', now(), now()
          FROM users u
         WHERE u.role = 'candidate'
        """
    )

    # Likewise, candidates could previously see every published exam. Enrol them in the
    # exams that already exist so nobody loses access to a paper they could already sit.
    op.execute(
        """
        INSERT INTO exam_enrollments (id, exam_id, candidate_id, assigned_at)
        SELECT gen_random_uuid(), e.id, u.id, now()
          FROM exams e
          CROSS JOIN users u
         WHERE u.role = 'candidate'
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_index(op.f('ix_exam_enrollments_exam_id'), table_name='exam_enrollments')
    op.drop_index(op.f('ix_exam_enrollments_candidate_id'), table_name='exam_enrollments')
    op.drop_table('exam_enrollments')
    op.drop_index(op.f('ix_login_access_requests_status'), table_name='login_access_requests')
    op.drop_index(op.f('ix_login_access_requests_candidate_id'), table_name='login_access_requests')
    op.drop_table('login_access_requests')
    # ### end Alembic commands ###
